
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView ConsoleTXT;
	
	private global::Gtk.Button SendBTN;
	
	private global::Gtk.Entry ChatInput;
	
	private global::Gtk.Label StatusLBL;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 300;
		this.GtkScrolledWindow.HeightRequest = 200;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.ConsoleTXT = new global::Gtk.TextView ();
		this.ConsoleTXT.CanFocus = true;
		this.ConsoleTXT.Name = "ConsoleTXT";
		this.GtkScrolledWindow.Add (this.ConsoleTXT);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w2.X = 44;
		w2.Y = 72;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SendBTN = new global::Gtk.Button ();
		this.SendBTN.WidthRequest = 70;
		this.SendBTN.CanFocus = true;
		this.SendBTN.Name = "SendBTN";
		this.SendBTN.UseUnderline = true;
		this.SendBTN.Label = global::Mono.Unix.Catalog.GetString ("Send");
		this.fixed1.Add (this.SendBTN);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SendBTN]));
		w3.X = 278;
		w3.Y = 43;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ChatInput = new global::Gtk.Entry ();
		this.ChatInput.WidthRequest = 230;
		this.ChatInput.CanFocus = true;
		this.ChatInput.Name = "ChatInput";
		this.ChatInput.IsEditable = true;
		this.ChatInput.InvisibleChar = '●';
		this.fixed1.Add (this.ChatInput);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ChatInput]));
		w4.X = 42;
		w4.Y = 43;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.StatusLBL = new global::Gtk.Label ();
		this.StatusLBL.Name = "StatusLBL";
		this.StatusLBL.LabelProp = global::Mono.Unix.Catalog.GetString ("status");
		this.fixed1.Add (this.StatusLBL);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.StatusLBL]));
		w5.X = 45;
		w5.Y = 21;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 328;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SendBTN.Clicked += new global::System.EventHandler (this.OnSendBTNClicked);
	}
}
